import Foundation

// Starter localization tables for Task 1. Later tasks add keys here as they
// add `L10nKey` constants in `Localization.swift`.

let enTable: [String: String] = [
    "language.system": "System",
    "settings.language": "Language",

    // Task 3: keyed alerts and error messages
    "alert.ntfs.onboarding": "NTFS drive \"%1$@\" detected. Turn on Settings → NTFS → \"Automatically mount external NTFS drives read-write\" to mount it read-write.",
    "alert.ntfs.installFailed": "NTFS driver installation failed or was canceled. \"%1$@\" remains read-only. Turn Settings → NTFS → \"Automatically mount external NTFS drives read-write\" off and back on to retry.",
    "alert.ntfs.mountFailed": "NTFS drive \"%1$@\" failed to mount read-write: %2$@. It remains read-only.",
    "error.connectivity.webdav.unauthorized": "WebDAV authentication failed (401 Unauthorized). Check the username, password, and account permission for this remote path.",
    "error.connectivity.webdav.forbidden": "WebDAV access was denied (403 Forbidden). Check whether this account can access the configured remote path.",
    "error.connectivity.webdav.notFound": "WebDAV remote path was not found. Check the remote path format and folder name.",
    "error.connectivity.unreachable": "%1$@ server is not reachable now. AutoVolume will retry after the network returns.",
    "error.connectivity.smb.unreachable": "SMB server is not reachable on port 445. AutoVolume will retry after the network returns.",
    "error.connectivity.afp.unreachable": "AFP server is not reachable on port 548. AutoVolume will retry after the network returns.",
    "error.connectivity.nfs.unreachable": "NFS server is not reachable on port 2049. Check the NFS service, firewall, export path, or network access.",
    "error.connectivity.testFailed": "%1$@ connection test failed with exit code %2$@.",
    "error.agent.mountCommandFailed": "Mount command failed with exit code %1$@.",
    "error.agent.mountUnresponsive": "Mount command succeeded, but the mounted volume did not respond. AutoVolume will retry on the next check.",

    // Task 4: full app UI
    "app.productName": "AutoVolume",

    "list.emptyTitle": "No Volumes",
    "list.emptyDescription": "Add a network volume to keep it connected.",
    "list.add": "Add",
    "list.edit": "Edit",
    "list.remove": "Remove",
    "list.mount": "Mount",
    "list.unmount": "Unmount",
    "list.alerts": "Alerts",
    "list.clearAlerts": "Clear",
    "list.noAlerts": "No alerts",
    "list.ntfsReadWriteBadge": "NTFS (Read-Write)",
    "list.intervalMinutesShort": "%1$@m",

    "editor.test": "Test Reachability",
    "editor.saveAndMount": "Save & Mount",
    "editor.save": "Save",
    "editor.cancel": "Cancel",
    "editor.name": "Name",
    "editor.server": "Server",
    "editor.remotePath": "Remote Path",
    "editor.remotePathHelp": "Use / for WebDAV root. For SMB, use share or share/folder, for example video or media/2026. Use /, not \\.",
    "editor.username": "Username",
    "editor.password": "Password",
    "editor.protocolLabel": "Protocol",
    "editor.mountPoint": "Mount Point",
    "editor.checkInterval": "Check Interval",
    "editor.everyMinutes": "Every %1$@ minutes",
    "editor.showPassword": "Show password",
    "editor.hidePassword": "Hide password",
    "editor.smbDialect": "SMB Range",
    "editor.smbMultichannel": "SMB3 Multichannel",
    "editor.smbAsyncReads": "Async directory reads",
    "editor.smbDialectAuto": "Auto (SMB2-SMB3)",

    "status.working": "Working...",
    "status.testing": "Testing...",
    "status.mounting": "Mounting...",
    "status.unmounting": "Unmounting...",
    "status.unmountSucceeded": "Unmounted.",
    "status.mountSucceeded": "Mount command succeeded.",
    "status.testSucceeded": "Connection, credentials, and remote path verified.",
    "status.saved": "Saved.",

    "menu.viewLogs": "View Logs",
    "menu.exportDiagnostics": "Export Diagnostics…",
    "menu.settings": "Settings",
    "menu.checkForUpdates": "Check for Updates…",
    "menu.quit": "Quit",

    "about.productName": "AutoVolume",
    "about.version": "Version %1$@ (%2$@)",
    "about.website": "Website",

    "alert.ok": "OK",
    "alert.exportDiagnosticsFailedTitle": "Failed to export diagnostics",

    "error.command.connectionTestFailed": "Connection test failed with exit code %1$@.",
    "error.command.mountFailed": "Mount failed with exit code %1$@.",
    "error.command.unmountFailed": "Unmount failed with exit code %1$@.",
    "error.command.finderFailed": "Finder failed with exit code %1$@.",
    "error.command.genericFailed": "Command failed.",

    "error.mount.webdavFinder5014": "macOS WebDAV/Finder mount service returned -5014. This is a macOS mount-layer failure, not a credential error; quit AutoVolume and restart macOS, which usually clears it.",
    "error.mount.webdavExit22": "WebDAV connectivity passed, but macOS Finder mount failed with exit code 22.",
    "error.mount.volumeNotResponding": "Mount command succeeded, but the mounted volume did not respond.",
    "error.mount.volumeNotRespondingAfterStaleClear": "Mount command succeeded, but the mounted volume did not respond after clearing a stale mount.",
    "error.mount.volumeNotRespondingAfterOccupiedClear": "Mount command succeeded, but the mounted volume did not respond after clearing an occupied mount point.",
    "error.mount.volumeNotRespondingAtRemotePath": "Mounted volume did not respond at the configured remote path.",

    "error.finder.notResponding": "Mounted folder is not responding at %1$@.",
    "error.finder.openFailed": "Mounted, but Finder could not open the target folder: %1$@",

    "error.mount.invalidRemotePath": "Invalid remote path. SMB requires a share name, for example sda1 or video.",
    "error.diagnostics.zipFailed": "Failed to create diagnostics zip: %1$@",

    "settings.sectionLogging": "Logging",
    "settings.logLevel": "Log Level",
    "settings.logLevelAll": "All",
    "settings.logLevelWarning": "Warning and above",
    "settings.logLevelError": "Errors only",
    "settings.logLevelHelp": "After adjusting, log entries below the selected level won't be written to the log file. The log file size limit is unchanged.",
    "settings.sectionMounting": "Mounting",
    "settings.openFinderAfterMount": "Open in Finder after a successful reconnect",
    "settings.openFinderAfterMountHelp": "When off, a successful automatic mount or reconnect won't open a Finder window.",
    "settings.sectionNTFS": "NTFS Drives",
    "settings.ntfsAutoMount": "Automatically mount external NTFS drives read-write",
    "settings.ntfsAutoMountHelp": "When on, the next NTFS drive you insert will trigger a one-time admin password prompt to install the bundled driver; never again after that. When off, macOS's native read-only mount is left untouched.",

    "settings.tab.general": "General",
    "settings.tab.ntfs": "NTFS",
    "settings.tab.about": "About"
]

let zhTable: [String: String] = [
    "language.system": "跟随系统",
    "settings.language": "语言",

    "alert.ntfs.onboarding": "检测到 NTFS 硬盘「%1$@」。前往 设置 → NTFS →「自动以读写方式挂载 NTFS 外接硬盘」开启后即可以读写方式挂载。",
    "alert.ntfs.installFailed": "NTFS 驱动安装失败或被取消，「%1$@」已保留为只读。可在 设置 → NTFS 中关闭再开启「自动以读写方式挂载 NTFS 外接硬盘」以重试。",
    "alert.ntfs.mountFailed": "NTFS 硬盘「%1$@」读写挂载失败：%2$@。已保留为只读。",
    "error.connectivity.webdav.unauthorized": "WebDAV 身份验证失败（401 Unauthorized）。请检查用户名、密码以及该远程路径的账号权限。",
    "error.connectivity.webdav.forbidden": "WebDAV 访问被拒绝（403 Forbidden）。请检查该账号是否有权访问所配置的远程路径。",
    "error.connectivity.webdav.notFound": "未找到 WebDAV 远程路径。请检查远程路径格式和文件夹名称。",
    "error.connectivity.unreachable": "%1$@ 服务器当前无法连接。网络恢复后 AutoVolume 会自动重试。",
    "error.connectivity.smb.unreachable": "SMB 服务器的 445 端口无法连接。网络恢复后 AutoVolume 会自动重试。",
    "error.connectivity.afp.unreachable": "AFP 服务器的 548 端口无法连接。网络恢复后 AutoVolume 会自动重试。",
    "error.connectivity.nfs.unreachable": "NFS 服务器的 2049 端口无法连接。请检查 NFS 服务、防火墙、导出路径或网络访问权限。",
    "error.connectivity.testFailed": "%1$@ 连接测试失败，退出码为 %2$@。",
    "error.agent.mountCommandFailed": "挂载命令失败，退出码为 %1$@。",
    "error.agent.mountUnresponsive": "挂载命令执行成功，但挂载的卷未响应。AutoVolume 将在下次检查时重试。",

    // Task 4: full app UI
    "app.productName": "智卷",

    "list.emptyTitle": "暂无卷",
    "list.emptyDescription": "添加网络卷后，智卷会保持它在线。",
    "list.add": "添加",
    "list.edit": "编辑",
    "list.remove": "移除",
    "list.mount": "挂载",
    "list.unmount": "卸载",
    "list.alerts": "告警",
    "list.clearAlerts": "清空",
    "list.noAlerts": "暂无告警",
    "list.ntfsReadWriteBadge": "NTFS（读写）",
    "list.intervalMinutesShort": "%1$@ 分钟",

    "editor.test": "测试连通性",
    "editor.saveAndMount": "保存并挂载",
    "editor.save": "保存",
    "editor.cancel": "取消",
    "editor.name": "名称",
    "editor.server": "服务器",
    "editor.remotePath": "远程路径",
    "editor.remotePathHelp": "WebDAV 根目录填 /。SMB 填共享名或共享名/文件夹，例如 video 或 media/2026。请使用 /，不要使用 \\。",
    "editor.username": "用户名",
    "editor.password": "密码",
    "editor.protocolLabel": "协议",
    "editor.mountPoint": "挂载点",
    "editor.checkInterval": "检查间隔",
    "editor.everyMinutes": "每 %1$@ 分钟",
    "editor.showPassword": "显示密码",
    "editor.hidePassword": "隐藏密码",
    "editor.smbDialect": "SMB 范围",
    "editor.smbMultichannel": "SMB3 多通道",
    "editor.smbAsyncReads": "异步目录读取",
    "editor.smbDialectAuto": "自动（SMB2-SMB3）",

    "status.working": "处理中...",
    "status.testing": "测试中...",
    "status.mounting": "挂载中...",
    "status.unmounting": "卸载中...",
    "status.unmountSucceeded": "已卸载。",
    "status.mountSucceeded": "挂载命令执行成功。",
    "status.testSucceeded": "服务器、账号密码和远程路径验证通过。",
    "status.saved": "已保存。",

    "menu.viewLogs": "查看日志",
    "menu.exportDiagnostics": "导出诊断信息…",
    "menu.settings": "设置",
    "menu.checkForUpdates": "检查更新…",
    "menu.quit": "退出",

    "about.productName": "智卷 AutoVolume",
    "about.version": "版本 %1$@ (%2$@)",
    "about.website": "官网",

    "alert.ok": "好",
    "alert.exportDiagnosticsFailedTitle": "导出诊断信息失败",

    "error.command.connectionTestFailed": "连通性测试失败，退出码为 %1$@。",
    "error.command.mountFailed": "挂载失败，退出码为 %1$@。",
    "error.command.unmountFailed": "卸载失败，退出码为 %1$@。",
    "error.command.finderFailed": "Finder 操作失败，退出码为 %1$@。",
    "error.command.genericFailed": "命令执行失败。",

    "error.mount.webdavFinder5014": "macOS WebDAV/Finder 挂载服务返回 -5014。AutoVolume 已验证到这是系统挂载层异常，不是账号密码错误；请先退出 AutoVolume 并重启 macOS，重启后通常会立即恢复。",
    "error.mount.webdavExit22": "WebDAV 连通性测试已通过，但 macOS Finder 挂载失败，退出码为 22。",
    "error.mount.volumeNotResponding": "挂载命令执行成功，但挂载的卷未响应。",
    "error.mount.volumeNotRespondingAfterStaleClear": "挂载命令执行成功，但清除失效挂载后，挂载的卷仍未响应。",
    "error.mount.volumeNotRespondingAfterOccupiedClear": "挂载命令执行成功，但清除被占用的挂载点后，挂载的卷仍未响应。",
    "error.mount.volumeNotRespondingAtRemotePath": "挂载的卷在配置的远程路径上未响应。",

    "error.finder.notResponding": "已挂载的文件夹在 %1$@ 未响应。",
    "error.finder.openFailed": "挂载后 Finder 无法打开目标目录：%1$@",

    "error.mount.invalidRemotePath": "远程路径无效。SMB 需要填写共享名，例如 sda1 或 video。",
    "error.diagnostics.zipFailed": "创建诊断压缩包失败：%1$@",

    "settings.sectionLogging": "日志",
    "settings.logLevel": "日志错误级别",
    "settings.logLevelAll": "全部",
    "settings.logLevelWarning": "警告及以上",
    "settings.logLevelError": "仅错误",
    "settings.logLevelHelp": "调整后，低于所选级别的日志将不会写入日志文件。日志文件大小限制不变。",
    "settings.sectionMounting": "挂载",
    "settings.openFinderAfterMount": "重连成功后自动在 Finder 中打开",
    "settings.openFinderAfterMountHelp": "关闭后，自动挂载或重连成功将不会自动打开 Finder 窗口。",
    "settings.sectionNTFS": "NTFS 硬盘",
    "settings.ntfsAutoMount": "自动以读写方式挂载 NTFS 外接硬盘",
    "settings.ntfsAutoMountHelp": "开启后，下次插入 NTFS 硬盘时会安装内置驱动（需要输入一次管理员密码），之后不再需要。关闭时保持 macOS 原生只读挂载。",

    "settings.tab.general": "通用",
    "settings.tab.ntfs": "NTFS",
    "settings.tab.about": "关于"
]

let koTable: [String: String] = [
    "language.system": "시스템 언어",
    "settings.language": "언어",

    "alert.ntfs.onboarding": "NTFS 드라이브 \"%1$@\"이(가) 감지되었습니다. 설정 → NTFS → \"외장 NTFS 드라이브를 읽기/쓰기로 자동 마운트\"를 켜면 읽기/쓰기 방식으로 마운트할 수 있습니다.",
    "alert.ntfs.installFailed": "NTFS 드라이버 설치에 실패했거나 취소되었습니다. \"%1$@\"은(는) 읽기 전용으로 유지됩니다. 설정 → NTFS에서 \"외장 NTFS 드라이브를 읽기/쓰기로 자동 마운트\"를 껐다가 다시 켜서 재시도하세요.",
    "alert.ntfs.mountFailed": "NTFS 드라이브 \"%1$@\" 읽기/쓰기 마운트에 실패했습니다: %2$@. 읽기 전용으로 유지됩니다.",
    "error.connectivity.webdav.unauthorized": "WebDAV 인증에 실패했습니다 (401 Unauthorized). 사용자 이름, 비밀번호, 이 원격 경로에 대한 계정 권한을 확인하세요.",
    "error.connectivity.webdav.forbidden": "WebDAV 접근이 거부되었습니다 (403 Forbidden). 이 계정이 설정된 원격 경로에 접근할 수 있는지 확인하세요.",
    "error.connectivity.webdav.notFound": "WebDAV 원격 경로를 찾을 수 없습니다. 원격 경로 형식과 폴더 이름을 확인하세요.",
    "error.connectivity.unreachable": "%1$@ 서버에 연결할 수 없습니다. 네트워크가 복구되면 AutoVolume이 다시 시도합니다.",
    "error.connectivity.smb.unreachable": "SMB 서버의 445번 포트에 연결할 수 없습니다. 네트워크가 복구되면 AutoVolume이 다시 시도합니다.",
    "error.connectivity.afp.unreachable": "AFP 서버의 548번 포트에 연결할 수 없습니다. 네트워크가 복구되면 AutoVolume이 다시 시도합니다.",
    "error.connectivity.nfs.unreachable": "NFS 서버의 2049번 포트에 연결할 수 없습니다. NFS 서비스, 방화벽, 내보내기 경로 또는 네트워크 접근 권한을 확인하세요.",
    "error.connectivity.testFailed": "%1$@ 연결 테스트가 종료 코드 %2$@(으)로 실패했습니다.",
    "error.agent.mountCommandFailed": "마운트 명령이 종료 코드 %1$@(으)로 실패했습니다.",
    "error.agent.mountUnresponsive": "마운트 명령은 성공했지만 마운트된 볼륨이 응답하지 않았습니다. AutoVolume이 다음 확인 시 다시 시도합니다.",

    // Task 4: full app UI
    "app.productName": "AutoVolume",

    "list.emptyTitle": "볼륨 없음",
    "list.emptyDescription": "네트워크 볼륨을 추가하면 계속 연결 상태를 유지합니다.",
    "list.add": "추가",
    "list.edit": "편집",
    "list.remove": "제거",
    "list.mount": "마운트",
    "list.unmount": "마운트 해제",
    "list.alerts": "알림",
    "list.clearAlerts": "지우기",
    "list.noAlerts": "경고 없음",
    "list.ntfsReadWriteBadge": "NTFS(읽기/쓰기)",
    "list.intervalMinutesShort": "%1$@분",

    "editor.test": "연결 테스트",
    "editor.saveAndMount": "저장 후 마운트",
    "editor.save": "저장",
    "editor.cancel": "취소",
    "editor.name": "이름",
    "editor.server": "서버",
    "editor.remotePath": "원격 경로",
    "editor.remotePathHelp": "WebDAV 루트는 / 를 사용하세요. SMB는 공유 이름 또는 공유 이름/폴더 형식(예: video 또는 media/2026)을 사용하세요. \\가 아닌 /를 사용하세요.",
    "editor.username": "사용자 이름",
    "editor.password": "비밀번호",
    "editor.protocolLabel": "프로토콜",
    "editor.mountPoint": "마운트 지점",
    "editor.checkInterval": "확인 간격",
    "editor.everyMinutes": "%1$@분마다",
    "editor.showPassword": "비밀번호 표시",
    "editor.hidePassword": "비밀번호 숨기기",
    "editor.smbDialect": "SMB 범위",
    "editor.smbMultichannel": "SMB3 다중 채널",
    "editor.smbAsyncReads": "비동기 디렉터리 읽기",
    "editor.smbDialectAuto": "자동 (SMB2-SMB3)",

    "status.working": "처리 중...",
    "status.testing": "테스트 중...",
    "status.mounting": "마운트 중...",
    "status.unmounting": "마운트 해제 중...",
    "status.unmountSucceeded": "마운트 해제됨.",
    "status.mountSucceeded": "마운트 명령이 성공했습니다.",
    "status.testSucceeded": "서버, 계정 정보, 원격 경로가 확인되었습니다.",
    "status.saved": "저장됨.",

    "menu.viewLogs": "로그 보기",
    "menu.exportDiagnostics": "진단 정보 내보내기…",
    "menu.settings": "설정",
    "menu.checkForUpdates": "업데이트 확인…",
    "menu.quit": "종료",

    "about.productName": "AutoVolume",
    "about.version": "버전 %1$@ (%2$@)",
    "about.website": "웹사이트",

    "alert.ok": "확인",
    "alert.exportDiagnosticsFailedTitle": "진단 정보 내보내기 실패",

    "error.command.connectionTestFailed": "연결 테스트가 종료 코드 %1$@(으)로 실패했습니다.",
    "error.command.mountFailed": "마운트가 종료 코드 %1$@(으)로 실패했습니다.",
    "error.command.unmountFailed": "마운트 해제가 종료 코드 %1$@(으)로 실패했습니다.",
    "error.command.finderFailed": "Finder 작업이 종료 코드 %1$@(으)로 실패했습니다.",
    "error.command.genericFailed": "명령 실행에 실패했습니다.",

    "error.mount.webdavFinder5014": "macOS WebDAV/Finder 마운트 서비스가 -5014를 반환했습니다. 이는 계정/비밀번호 오류가 아니라 macOS 마운트 계층의 오류입니다. AutoVolume을 종료하고 macOS를 재시작하면 대부분 해결됩니다.",
    "error.mount.webdavExit22": "WebDAV 연결 테스트는 통과했지만 macOS Finder 마운트가 종료 코드 22로 실패했습니다.",
    "error.mount.volumeNotResponding": "마운트 명령은 성공했지만 마운트된 볼륨이 응답하지 않았습니다.",
    "error.mount.volumeNotRespondingAfterStaleClear": "마운트 명령은 성공했지만, 오래된 마운트를 정리한 후에도 볼륨이 응답하지 않았습니다.",
    "error.mount.volumeNotRespondingAfterOccupiedClear": "마운트 명령은 성공했지만, 사용 중이던 마운트 지점을 정리한 후에도 볼륨이 응답하지 않았습니다.",
    "error.mount.volumeNotRespondingAtRemotePath": "마운트된 볼륨이 설정된 원격 경로에서 응답하지 않았습니다.",

    "error.finder.notResponding": "마운트된 폴더가 %1$@에서 응답하지 않습니다.",
    "error.finder.openFailed": "마운트되었지만 Finder가 대상 폴더를 열지 못했습니다: %1$@",

    "error.mount.invalidRemotePath": "원격 경로가 올바르지 않습니다. SMB는 공유 이름이 필요합니다(예: sda1 또는 video).",
    "error.diagnostics.zipFailed": "진단 zip 파일 생성에 실패했습니다: %1$@",

    "settings.sectionLogging": "로그",
    "settings.logLevel": "로그 수준",
    "settings.logLevelAll": "전체",
    "settings.logLevelWarning": "경고 이상",
    "settings.logLevelError": "오류만",
    "settings.logLevelHelp": "조정 후에는 선택한 수준보다 낮은 로그가 로그 파일에 기록되지 않습니다. 로그 파일 크기 제한은 변경되지 않습니다.",
    "settings.sectionMounting": "마운트",
    "settings.openFinderAfterMount": "재연결 성공 시 Finder에서 자동으로 열기",
    "settings.openFinderAfterMountHelp": "끄면 자동 마운트 또는 재연결에 성공해도 Finder 창이 자동으로 열리지 않습니다.",
    "settings.sectionNTFS": "NTFS 드라이브",
    "settings.ntfsAutoMount": "외장 NTFS 드라이브를 읽기/쓰기로 자동 마운트",
    "settings.ntfsAutoMountHelp": "켜면 다음에 NTFS 드라이브를 연결할 때 관리자 비밀번호를 한 번 입력하여 내장 드라이버를 설치하며, 이후에는 다시 필요하지 않습니다. 끄면 macOS의 기본 읽기 전용 마운트가 그대로 유지됩니다.",

    "settings.tab.general": "일반",
    "settings.tab.ntfs": "NTFS",
    "settings.tab.about": "정보"
]

let jaTable: [String: String] = [
    "language.system": "システムに従う",
    "settings.language": "言語",

    "alert.ntfs.onboarding": "NTFS ドライブ「%1$@」を検出しました。設定 → NTFS →「外付け NTFS ドライブを読み書きで自動マウント」を有効にすると読み書きでマウントできます。",
    "alert.ntfs.installFailed": "NTFS ドライバのインストールに失敗またはキャンセルされました。「%1$@」は読み取り専用のままです。設定 → NTFS で「外付け NTFS ドライブを読み書きで自動マウント」をオフにしてから再度オンにして再試行してください。",
    "alert.ntfs.mountFailed": "NTFS ドライブ「%1$@」の読み書きマウントに失敗しました: %2$@。読み取り専用のままです。",
    "error.connectivity.webdav.unauthorized": "WebDAV の認証に失敗しました（401 Unauthorized）。ユーザー名、パスワード、このリモートパスへのアカウント権限を確認してください。",
    "error.connectivity.webdav.forbidden": "WebDAV へのアクセスが拒否されました（403 Forbidden）。このアカウントが設定されたリモートパスにアクセスできるか確認してください。",
    "error.connectivity.webdav.notFound": "WebDAV のリモートパスが見つかりませんでした。リモートパスの形式とフォルダ名を確認してください。",
    "error.connectivity.unreachable": "%1$@ サーバーに接続できません。ネットワークが復旧すると AutoVolume が再試行します。",
    "error.connectivity.smb.unreachable": "SMB サーバーのポート 445 に接続できません。ネットワークが復旧すると AutoVolume が再試行します。",
    "error.connectivity.afp.unreachable": "AFP サーバーのポート 548 に接続できません。ネットワークが復旧すると AutoVolume が再試行します。",
    "error.connectivity.nfs.unreachable": "NFS サーバーのポート 2049 に接続できません。NFS サービス、ファイアウォール、エクスポートパス、ネットワークアクセスを確認してください。",
    "error.connectivity.testFailed": "%1$@ 接続テストが終了コード %2$@ で失敗しました。",
    "error.agent.mountCommandFailed": "マウントコマンドが終了コード %1$@ で失敗しました。",
    "error.agent.mountUnresponsive": "マウントコマンドは成功しましたが、マウントされたボリュームが応答しませんでした。次回のチェックで AutoVolume が再試行します。",

    // Task 4: full app UI
    "app.productName": "AutoVolume",

    "list.emptyTitle": "ボリュームなし",
    "list.emptyDescription": "ネットワークボリュームを追加すると、接続状態を保ちます。",
    "list.add": "追加",
    "list.edit": "編集",
    "list.remove": "削除",
    "list.mount": "マウント",
    "list.unmount": "アンマウント",
    "list.alerts": "アラート",
    "list.clearAlerts": "クリア",
    "list.noAlerts": "アラートなし",
    "list.ntfsReadWriteBadge": "NTFS（読み書き）",
    "list.intervalMinutesShort": "%1$@分",

    "editor.test": "接続テスト",
    "editor.saveAndMount": "保存してマウント",
    "editor.save": "保存",
    "editor.cancel": "キャンセル",
    "editor.name": "名前",
    "editor.server": "サーバー",
    "editor.remotePath": "リモートパス",
    "editor.remotePathHelp": "WebDAV のルートは / を使用してください。SMB は共有名または共有名/フォルダ（例: video や media/2026）を使用してください。\\ ではなく / を使用してください。",
    "editor.username": "ユーザー名",
    "editor.password": "パスワード",
    "editor.protocolLabel": "プロトコル",
    "editor.mountPoint": "マウントポイント",
    "editor.checkInterval": "確認間隔",
    "editor.everyMinutes": "%1$@ 分ごと",
    "editor.showPassword": "パスワードを表示",
    "editor.hidePassword": "パスワードを隠す",
    "editor.smbDialect": "SMB 範囲",
    "editor.smbMultichannel": "SMB3 マルチチャネル",
    "editor.smbAsyncReads": "非同期ディレクトリ読み取り",
    "editor.smbDialectAuto": "自動 (SMB2-SMB3)",

    "status.working": "処理中...",
    "status.testing": "テスト中...",
    "status.mounting": "マウント中...",
    "status.unmounting": "アンマウント中...",
    "status.unmountSucceeded": "アンマウントしました。",
    "status.mountSucceeded": "マウントコマンドが成功しました。",
    "status.testSucceeded": "サーバー、認証情報、リモートパスを確認しました。",
    "status.saved": "保存しました。",

    "menu.viewLogs": "ログを表示",
    "menu.exportDiagnostics": "診断情報を書き出す…",
    "menu.settings": "設定",
    "menu.checkForUpdates": "アップデートを確認…",
    "menu.quit": "終了",

    "about.productName": "AutoVolume",
    "about.version": "バージョン %1$@ (%2$@)",
    "about.website": "ウェブサイト",

    "alert.ok": "OK",
    "alert.exportDiagnosticsFailedTitle": "診断情報の書き出しに失敗しました",

    "error.command.connectionTestFailed": "接続テストが終了コード %1$@ で失敗しました。",
    "error.command.mountFailed": "マウントが終了コード %1$@ で失敗しました。",
    "error.command.unmountFailed": "アンマウントが終了コード %1$@ で失敗しました。",
    "error.command.finderFailed": "Finder の操作が終了コード %1$@ で失敗しました。",
    "error.command.genericFailed": "コマンドが失敗しました。",

    "error.mount.webdavFinder5014": "macOS の WebDAV/Finder マウントサービスが -5014 を返しました。これはアカウントやパスワードの誤りではなく、macOS のマウント層の不具合です。AutoVolume を終了して macOS を再起動すると、通常はすぐに解消します。",
    "error.mount.webdavExit22": "WebDAV の接続テストは成功しましたが、macOS Finder のマウントが終了コード 22 で失敗しました。",
    "error.mount.volumeNotResponding": "マウントコマンドは成功しましたが、マウントされたボリュームが応答しませんでした。",
    "error.mount.volumeNotRespondingAfterStaleClear": "マウントコマンドは成功しましたが、古いマウントを解除した後もボリュームが応答しませんでした。",
    "error.mount.volumeNotRespondingAfterOccupiedClear": "マウントコマンドは成功しましたが、使用中だったマウントポイントを解除した後もボリュームが応答しませんでした。",
    "error.mount.volumeNotRespondingAtRemotePath": "設定されたリモートパスでマウントされたボリュームが応答しませんでした。",

    "error.finder.notResponding": "マウントされたフォルダが %1$@ で応答していません。",
    "error.finder.openFailed": "マウントされましたが、Finder が対象フォルダを開けませんでした: %1$@",

    "error.mount.invalidRemotePath": "リモートパスが無効です。SMB では共有名が必要です（例: sda1 や video）。",
    "error.diagnostics.zipFailed": "診断用 zip の作成に失敗しました: %1$@",

    "settings.sectionLogging": "ログ",
    "settings.logLevel": "ログレベル",
    "settings.logLevelAll": "すべて",
    "settings.logLevelWarning": "警告以上",
    "settings.logLevelError": "エラーのみ",
    "settings.logLevelHelp": "変更後、選択したレベルより低いログはログファイルに書き込まれません。ログファイルのサイズ上限は変わりません。",
    "settings.sectionMounting": "マウント",
    "settings.openFinderAfterMount": "再接続に成功したら Finder で自動的に開く",
    "settings.openFinderAfterMountHelp": "オフにすると、自動マウントや再接続が成功しても Finder ウィンドウは自動的に開きません。",
    "settings.sectionNTFS": "NTFS ドライブ",
    "settings.ntfsAutoMount": "外付け NTFS ドライブを読み書きで自動マウント",
    "settings.ntfsAutoMountHelp": "オンにすると、次に NTFS ドライブを接続したときに管理者パスワードを一度入力して内蔵ドライバーをインストールします。以降は不要です。オフのままだと、macOS 標準の読み取り専用マウントが維持されます。",

    "settings.tab.general": "一般",
    "settings.tab.ntfs": "NTFS",
    "settings.tab.about": "このアプリについて"
]

let ruTable: [String: String] = [
    "language.system": "Как в системе",
    "settings.language": "Язык",

    "alert.ntfs.onboarding": "Обнаружен диск NTFS «%1$@». Включите в настройках NTFS → «Автоматически подключать внешние диски NTFS для чтения и записи», чтобы подключить его для чтения и записи.",
    "alert.ntfs.installFailed": "Не удалось установить драйвер NTFS, либо установка была отменена. «%1$@» остаётся доступным только для чтения. Выключите и снова включите в настройках NTFS → «Автоматически подключать внешние диски NTFS для чтения и записи», чтобы повторить попытку.",
    "alert.ntfs.mountFailed": "Не удалось подключить диск NTFS «%1$@» для чтения и записи: %2$@. Диск остаётся доступным только для чтения.",
    "error.connectivity.webdav.unauthorized": "Ошибка аутентификации WebDAV (401 Unauthorized). Проверьте имя пользователя, пароль и права доступа учётной записи к этому удалённому пути.",
    "error.connectivity.webdav.forbidden": "Доступ к WebDAV запрещён (403 Forbidden). Проверьте, есть ли у этой учётной записи доступ к настроенному удалённому пути.",
    "error.connectivity.webdav.notFound": "Удалённый путь WebDAV не найден. Проверьте формат удалённого пути и имя папки.",
    "error.connectivity.unreachable": "Сервер %1$@ сейчас недоступен. AutoVolume повторит попытку после восстановления сети.",
    "error.connectivity.smb.unreachable": "Сервер SMB недоступен на порту 445. AutoVolume повторит попытку после восстановления сети.",
    "error.connectivity.afp.unreachable": "Сервер AFP недоступен на порту 548. AutoVolume повторит попытку после восстановления сети.",
    "error.connectivity.nfs.unreachable": "Сервер NFS недоступен на порту 2049. Проверьте службу NFS, брандмауэр, экспортируемый путь и доступ к сети.",
    "error.connectivity.testFailed": "Проверка соединения %1$@ завершилась с кодом выхода %2$@.",
    "error.agent.mountCommandFailed": "Команда подключения завершилась с кодом выхода %1$@.",
    "error.agent.mountUnresponsive": "Команда подключения выполнена успешно, но подключённый том не отвечает. AutoVolume повторит попытку при следующей проверке.",

    // Task 4: full app UI
    "app.productName": "AutoVolume",

    "list.emptyTitle": "Нет томов",
    "list.emptyDescription": "Добавьте сетевой том, чтобы AutoVolume поддерживал его подключение.",
    "list.add": "Добавить",
    "list.edit": "Изменить",
    "list.remove": "Удалить",
    "list.mount": "Подключить",
    "list.unmount": "Отключить",
    "list.alerts": "Оповещения",
    "list.clearAlerts": "Очистить",
    "list.noAlerts": "Нет оповещений",
    "list.ntfsReadWriteBadge": "NTFS (чтение/запись)",
    "list.intervalMinutesShort": "%1$@ мин",

    "editor.test": "Проверить соединение",
    "editor.saveAndMount": "Сохранить и подключить",
    "editor.save": "Сохранить",
    "editor.cancel": "Отмена",
    "editor.name": "Имя",
    "editor.server": "Сервер",
    "editor.remotePath": "Удалённый путь",
    "editor.remotePathHelp": "Для корня WebDAV используйте /. Для SMB используйте имя общего ресурса или имя_ресурса/папка, например video или media/2026. Используйте /, а не \\.",
    "editor.username": "Имя пользователя",
    "editor.password": "Пароль",
    "editor.protocolLabel": "Протокол",
    "editor.mountPoint": "Точка подключения",
    "editor.checkInterval": "Интервал проверки",
    "editor.everyMinutes": "Интервал: %1$@ мин.",
    "editor.showPassword": "Показать пароль",
    "editor.hidePassword": "Скрыть пароль",
    "editor.smbDialect": "Диапазон SMB",
    "editor.smbMultichannel": "Многоканальность SMB3",
    "editor.smbAsyncReads": "Асинхронное чтение каталогов",
    "editor.smbDialectAuto": "Авто (SMB2-SMB3)",

    "status.working": "Выполняется...",
    "status.testing": "Проверка...",
    "status.mounting": "Подключение...",
    "status.unmounting": "Отключение...",
    "status.unmountSucceeded": "Отключено.",
    "status.mountSucceeded": "Команда подключения выполнена успешно.",
    "status.testSucceeded": "Сервер, учётные данные и удалённый путь проверены.",
    "status.saved": "Сохранено.",

    "menu.viewLogs": "Просмотреть журнал",
    "menu.exportDiagnostics": "Экспортировать диагностику…",
    "menu.settings": "Настройки",
    "menu.checkForUpdates": "Проверить обновления…",
    "menu.quit": "Выйти",

    "about.productName": "AutoVolume",
    "about.version": "Версия %1$@ (%2$@)",
    "about.website": "Веб-сайт",

    "alert.ok": "ОК",
    "alert.exportDiagnosticsFailedTitle": "Не удалось экспортировать диагностику",

    "error.command.connectionTestFailed": "Проверка соединения завершилась с кодом выхода %1$@.",
    "error.command.mountFailed": "Подключение завершилось с кодом выхода %1$@.",
    "error.command.unmountFailed": "Отключение завершилось с кодом выхода %1$@.",
    "error.command.finderFailed": "Операция Finder завершилась с кодом выхода %1$@.",
    "error.command.genericFailed": "Команда завершилась с ошибкой.",

    "error.mount.webdavFinder5014": "Служба подключения WebDAV/Finder в macOS вернула ошибку -5014. Это сбой уровня подключения macOS, а не неверные учётные данные; выйдите из AutoVolume и перезагрузите macOS — обычно это сразу устраняет проблему.",
    "error.mount.webdavExit22": "Проверка соединения WebDAV прошла успешно, но подключение через Finder в macOS завершилось с кодом выхода 22.",
    "error.mount.volumeNotResponding": "Команда подключения выполнена успешно, но подключённый том не отвечает.",
    "error.mount.volumeNotRespondingAfterStaleClear": "Команда подключения выполнена успешно, но том не отвечает даже после устранения устаревшего подключения.",
    "error.mount.volumeNotRespondingAfterOccupiedClear": "Команда подключения выполнена успешно, но том не отвечает даже после освобождения занятой точки подключения.",
    "error.mount.volumeNotRespondingAtRemotePath": "Подключённый том не отвечает по настроенному удалённому пути.",

    "error.finder.notResponding": "Подключённая папка не отвечает по адресу %1$@.",
    "error.finder.openFailed": "Том подключён, но Finder не смог открыть целевую папку: %1$@",

    "error.mount.invalidRemotePath": "Недопустимый удалённый путь. Для SMB требуется имя общего ресурса, например sda1 или video.",
    "error.diagnostics.zipFailed": "Не удалось создать zip-архив диагностики: %1$@",

    "settings.sectionLogging": "Журнал",
    "settings.logLevel": "Уровень журнала",
    "settings.logLevelAll": "Все",
    "settings.logLevelWarning": "Предупреждения и выше",
    "settings.logLevelError": "Только ошибки",
    "settings.logLevelHelp": "После изменения записи журнала ниже выбранного уровня не будут записываться в файл журнала. Ограничение размера файла журнала не меняется.",
    "settings.sectionMounting": "Подключение",
    "settings.openFinderAfterMount": "Открывать в Finder после успешного переподключения",
    "settings.openFinderAfterMountHelp": "Если выключено, успешное автоматическое подключение или переподключение не будет открывать окно Finder.",
    "settings.sectionNTFS": "Диски NTFS",
    "settings.ntfsAutoMount": "Автоматически подключать внешние диски NTFS для чтения и записи",
    "settings.ntfsAutoMountHelp": "Если включено, при следующем подключении диска NTFS будет предложено один раз ввести пароль администратора для установки встроенного драйвера; повторно это не потребуется. Если выключено, используется стандартное подключение macOS только для чтения.",

    "settings.tab.general": "Общие",
    "settings.tab.ntfs": "NTFS",
    "settings.tab.about": "О программе"
]
